services:
  discord-bot:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./public:/app/public:ro
    ports:
      - "80:8080"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge